### ISSUE TITLE
Implementation of `IBlobStorage.WriteAsync` does not honor the `append` hint value in `FluentFtpBlobStorage`

### ISSUE THREAD

**Issue by candoumbe** [robinrodricks/FluentStorage#23]
The current implementation of `IBlobStorage.WriteAsync`does not honor the `append` hint value in [FluentStorage.FTP implementation](https://github.com/robinrodricks/FluentStorage/blob/33c5966690c8536fe9cafb92f60253424c877b7b/FluentStorage.FTP/FluentFtpBlobStorage.cs#L165)
```csharp

		public async Task WriteAsync(string fullPath, Stream dataStream,
		   bool append = false, CancellationToken cancellationToken = default) {
			AsyncFtpClient client = await GetClientAsync().ConfigureAwait(false);

			await retryPolicy.ExecuteAsync(async () => {
				using (Stream dest = await client.OpenWrite(fullPath, FtpDataType.Binary, true).ConfigureAwait(false)) {
					await dataStream.CopyToAsync(dest).ConfigureAwait(false);
				}
			}).ConfigureAwait(false);
		}
```

I think the stream should be created using `client.OpenAppend` when the parameter `append` is `true` and `client.OpenWrite` otherwise.

**Comment by candoumbe** [comment]
@robinrodricks 
I started working on fixing this bug : https://github.com/robinrodricks/FluentStorage/compare/develop...candoumbe:FluentStorage:hotfix/ftpblobstorage-should-append-or-write-depending-on-append-parameter-value

Unfortunately, I currently encounter an issue when using [TestContainers](https://www.nuget.org/packages/Testcontainers) to setup [a FTP fixture (using pure-ftpd docker image)](https://github.com/robinrodricks/FluentStorage/compare/develop...candoumbe:FluentStorage:hotfix/ftpblobstorage-should-append-or-write-depending-on-append-parameter-value#diff-3f8b99aa73c3b9793a5b5b8bb9cdb5c1ab34bd5629a93a1dc16920205f5488ce) but for now the test fails.

The test passes if I setup a container for the ftp server  with a docker compose like this:
```yaml
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30059:30000-30059"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/home/<my folder>/data:/home/k2/data:rw"
      - "/home/<my folder>/passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: k2
      FTP_USER_PASS: k2
      FTP_USER_HOME: /home/user/
      FTP_MAX_CLIENTS: 50
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
```
